/**
 * Données liées aux événements
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * une action
 */
export interface Action extends models.Objet {
    codeEtat?: string;

    commentaire?: string;

    /**
     * horodate de derniere modification format 2012-04-23T18:25:43.511Z
     */
    horodateDebutExecution?: Date;

    /**
     * horodate de derniere modification format 2012-04-23T18:25:43.511Z
     */
    horodateFinExecution?: Date;

    ordre?: number;

}
