/**
 * Données liées aux événements
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Catégorie de modèles d'événements
 */
export interface CategorieEvenement extends models.Objet {
    /**
     * Map codeInfo modele evt -> resume modele evt
     */
    resumesModelesEvenements?: { [key: string]: models.Objet; };

}
