/**
 * Opérations liées aux stratégies
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Map des circuits de viabilité hivernale
 */
export interface CircuitsVH {
    /**
     * état d'activation de la viabilité hivernales
     */
    actif?: boolean;

    /**
     * Map codeInfo -> Circuit de viabilité
     */
    circuits?: { [key: string]: models.CircuitVH; };

}
