/**
 * Opérations liées aux stratégies
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Etat de la viabilite hivernale pour un circuit de viabilité hivernale
 */
export interface CircuitVH extends models.Objet {
    /**
     * code info de la valeur d'énumération représentant l'état CCH
     */
    codeCCH?: string;

    /**
     * code info de la valeur d'énumération représentant l'état CCH 2
     */
    codeCCH2?: string;

    /**
     * code info de la valeur d'énumération indiquant si des eqp spéciaux sont requis
     */
    codeEquipementsSpeciaux?: string;

    /**
     * code info de la valeur d'énumération représentant l'état météo
     */
    codeMeteo?: string;

    /**
     * code info de la valeur d'énumération représentant le traitement de la chaussée
     */
    codeTraitement?: string;

    /**
     * code info de la valeur d'énumération représentant la tendance
     */
    codeTendance?: string;

    /**
     * code info de la valeur d'énumération représentant l'état de la chaussée
     */
    codeEtatChaussee?: string;

    /**
     * code info de la valeur d'énumération représentant l'état du vent
     */
    codeVent?: string;

    /**
     * valeur de la température
     */
    temperature?: number;

    /**
     * code info de la valeur d'enumeration representant
     */
    commentaireInterne?: string;

    /**
     * nom de la classe java
     */
    commentaire?: string;

}
