/**
 * Données liées aux macro commandes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * une condition de contrôle d'une macro commande
 */
export interface ConditionControle extends models.Objet {
    /**
     * resultat de l'évaluation de la condition
     */
    resultat?: boolean;

}
