/**
 * Opérations liées aux stratégies
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Demande de modification de groupe d'événements
 */
export interface DemandeModificationGroupeEvenement {
    /**
     * identifiant du groupe à modifier
     */
    identifiant?: number;

    /**
     * liste des identifants des evenements à insérer dans le groupe
     */
    aInserer?: Array<number>;

    /**
     * liste des identifants des evenements à retirer du groupe
     */
    aSupprimer?: Array<number>;

}
