/**
 * Données liées aux événements
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * une emprise
 */
export interface Emprise extends models.Objet {
    /**
     * code de la section de l'emprise
     */
    codeSection?: string;

    /**
     * Pr de début de l'emprise
     */
    prDebut?: models.Pr;

    /**
     * Pr de fin de l'emprise
     */
    prFin?: models.Pr;

    /**
     * liste des codes des voies de l'emprise
     */
    voies?: Array<string>;

}
