/**
 * Opérations liées aux stratégies
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * un format de message
 */
export interface FormatMessage extends models.Objet {
    /**
     * nombre de lignes
     */
    nbLignes?: number;

    /**
     * nombre de colonne
     */
    nbColonnes?: number;

    /**
     * nombre de colonne
     */
    nbColonnesPannonceau?: number;

    /**
     * code info du modèle d'équipement
     */
    codeModeleEquipement?: string;

}
