/**
 * Données liées aux ressources
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * un groupe d'astreinte
 */
export interface GroupeAstreinte extends models.Objet {
    /**
     * numero par défaut de l'astreinte
     */
    numeroParDefaut?: string;

    /**
     * information de planification de la diffusion d'un message vocal
     */
    planificationMessageVocal?: models.Planification;

    /**
     * code du message vocal planifié
     */
    codeMessageVocalPlanifie?: string;

    /** 
     * indique s'il s'agit d'une astreinte multiple
    */
    multiple?: boolean;

}
