/**
 * Données liées aux événements
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * un localisant
 */
export interface Localisant extends models.Objet {
    /**
     * code du mode de localisation
     */
    codeModeLocalisation?: string;

    /**
     * code de la zone du localisant
     */
    codeZone?: string;

    /**
     * code du lieu du localisant
     */
    codelieu?: string;

    /**
     * section de debut
     */
    codeSectionDebut?: string;

    /**
     * sens de debut
     */
    codeSensDebut?: string;

    prDebut?: models.Pr;

    /**
     * section de fin
     */
    codeSectionFin?: string;

    /**
     * sens de fin
     */
    codeSensFin?: string;

    prFin?: models.Pr;

    /**
     * implique les deux sens
     */
    impliqueDeuxSens?: boolean;

    emprises?: Array<models.Emprise>;

    emprisesSensInverse?: Array<models.Emprise>;

}
