/**
 * Données liées aux macro commandes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * une macro commande
 */
export interface MacroCommande extends models.Objet {
    /**
     * code info du modele de la macro
     */
    code_modele?: string;

    /**
     * code info de l'etat de la macro
     */
    code_etat?: string;

    /**
     * horodate de début d'exécution de la macro
     */
    horodateDebut?: Date;

    /**
     * pourcentage d'avancement de la macro
     */
    pourcentage_avancement?: number;

    /**
     * liste des conditions de contrôles de la macro
     */
    preconditions?: Array<models.ConditionControle>;

    /**
     * liste des étapes de la macro
     */
    etapes?: Array<models.Etape>;

}
