/**
 * Opérations liées aux stratégies
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Map code info equipement => Messages pour cet equipement 
 */
export interface MessagesEquipementsStrategies {
    /**
     * Map identifiant ->  Messages de l'Equipement
     */
    messagesEquipements?: { [key: string]: models.MessagesEquipementStrategie; };

}
