/**
 * Opérations liées aux stratégies
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * un message de stratégie
 */
export interface MessageStrategie extends models.Objet {
    /**
     * identifiant de la stratégie à laquelle est rattaché le message
     */
    identifiantStrategie?: number;

    /**
     * nom de la stratégie
     */
    nomStrategie?: string;

    /**
     * code de l'équipement
     */
    codeEquipement?: string;

    /**
     * code du format de message
     */
    codeFormatMessage?: string;

    /**
     * Map codeInfo modele variable -> valeur variable
     */
    valeurs?: models.ValeursVariables;

}
