/**
 * Opérations liées aux stratégies
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * une notification de màj plan d'action d'evt
 */
export interface NotificationPacEvenement {
    /**
     * UPDATED,DELETED
     */
    typeNotification?: NotificationPacEvenement.TypeNotificationEnum;

    pacEvenement?: models.PacEvenement;

}
export namespace NotificationPacEvenement {
    export enum TypeNotificationEnum {
        UPDATED = <any> 'UPDATED',
        DELETED = <any> 'DELETED'
    }
}
