/**
 * Données liées aux ressources
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';


/**
 * un planning d'astreinte
 */
export interface PlanningAstreinte extends models.Objet {
    /**
     * code du groupe d'astreinte
     */
    codeAstreinte?: string;


    /**
     * code du modèle groupe d'astreinte
     */
    codeModeleAstreinte?: string;


    /**
     * horodate de création format 2012-04-23T18:25:43.511Z
     */
    horodateDebut?: Date;

    /**
     * horodate de création format 2012-04-23T18:25:43.511Z
     */
    horodateFin?: Date;

    /**
     * cellules du planning d'astreinte
     */
    cellules?: Array<models.CelluleAstreinte>;

    /** 
     * regroupement des cellules d'astreintes en plages horaires disjointes
    */
    plages?: Array<models.PlageHoraireAstreinte>;

    /** 
     * nombre max de cellule par plage horaire
    */
    maxCelluleParPlage?: number;


}
