/**
 * Données liées aux événements
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * un pr type
 */
export interface PrType extends models.Objet {
    /**
     * code de l'axe
     */
    codeAxe?: string;

    /**
     * numéro du pr type
     */
    numero?: number;

    /**
     * l'abscisse max en sens 1
     */
    distancePrTypeSuivantSensCroissant?: number;

    /**
     * l'abscisse max en sens 2
     */
    distancePrTypeSuivantSensDecroissant?: number;

}
