/**
 * Opérations liées aux stratégies
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * résumé d'une macro commande
 */
export interface ResumeMacroCommande extends models.Objet {
    /**
     * code info du modele de la macro
     */
    codeModele?: string;

    /**
     * code info de l'etat de la macro
     */
    codeEtat?: string;

    /**
     * horodate de début d'exécution de la macro
     */
    horodateDebut?: Date;

}
