/**
 * Données liées aux macro commandes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * résumé d'un modèle de macro commande
 */
export interface ResumeModeleMacroCommande extends models.Objet {
    /**
     * indique si la macro peut être lancé manuellement
     */
    virtuel?: boolean;

    /**
     * code du modèle de macro hérité
     */
    codeModeleHerite?: string;

    /**
     * information de planification de la macro
     */
    planification?: models.Planification;




    /**
     * code info de l'etat de l'instance de la macro
     */
    codeEtat?: string;

    /** 
     * etat de selection du modèle de macro
    */
    isSelect?: boolean

}
