/**
 * Opérations liées à la prise de poste
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';
import {Objet} from './Objet';

/**
 * une session sae
 */
export interface SessionSae extends Objet {
    /**
     * login de l'opérateur
     */
    login?: string;

    /**
     * nom de l'opérateur
     */
    nom?: string;

    /**
     * prénom de l'opérateur
     */
    prenom?: string;

    /**
     * code info du poste opérateur
     */
    poste?: string;

    /**
     * adresse ip du poste client
     */
    adresseIp?: string;


    /**
     * Map codeInfo droit -> droit
     */
    droits?: { [key: string]: Objet; };

}
