/**
 * Données liées aux événements
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Valeur possible des attributs/parametres/variables Agora
 */
export interface ValeurPossible extends models.Objet {
    /**
     * code info de l'enumeration
     */
    codeEnumeration?: string;

    /**
     * expression régulière de la chaine
     */
    expressionReguliere?: string;

    /**
     * longueur de chaine maximale
     */
    longueurMax?: number;

    /**
     * valeur numérique minimale
     */
    min?: number;

    /**
     * valeur numérique maximale
     */
    max?: number;

    /**
     * une requête
     */
    requete?: string;

    /**
     * code info de la valeur d'enumeration representant
     */
    codeType?: string;

    /**
     * nom de la classe java
     */
    typeJava?: string;

}
